kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: kind-cluster
nodes:
- role: control-plane
  # add a mount from /path/to/my/files on the host to /files on the node
  extraMounts:
    # repo
  - hostPath: /home/project/llm-ray/
    containerPath: /home/project/llm-ray/
    # dataset
  - hostPath: /home/resources/dataset/
    containerPath: /home/resources/dataset/
    # model
  - hostPath: /home/resources/model
    containerPath: /home/resources/model
    # save path
  - hostPath: /home/resources/outputs/
    containerPath: /home/resources/outputs/
    # checkpoint path
  - hostPath: /home/resources/checkpoints/
    containerPath: /home/resources/checkpoints/